# Generated by Django 3.2 on 2022-05-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwe', '0002_result_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='category_name',
        ),
        migrations.AddField(
            model_name='result',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qwe.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
